/* =============================================================================
   CONFERENCE PRESENTATIONS
   Source: the Kakraba Research Group conferences page
   (kakraba-research-group.vercel.app/conferences), which is the CV's
   "Conference Presentations" list with spelling cleaned up: 62 entries,
   2015–2026. Links are the CV's own media-coverage URLs, attached to the
   talk each article covers (e.g. the EKU Spark Talk video).
   ========================================================================== */

export type PresentationCategory = "talk" | "poster" | "panel" | "workshop";

export type PresentationLink = { label: string; href: string };

export type Presentation = {
  year: number;
  /** As printed on the CV: an exact date, a month, or a season. */
  date: string;
  /** The CV's role label, e.g. "Keynote speaker" or "Invited poster". */
  role: string;
  category: PresentationCategory;
  title: string;
  venue: string;
  authors: string;
  links?: PresentationLink[];
  /** His role on student-led posters, as printed on the CV. */
  mentorRole?: string;
};

export const presentationCategories: { id: PresentationCategory; label: string }[] = [
  { id: "talk", label: "Talks" },
  { id: "poster", label: "Posters" },
  { id: "panel", label: "Panels" },
  { id: "workshop", label: "Workshops" },
];

export const presentations: Presentation[] = [
  {
    year: 2026,
    date: "September 11, 2026",
    role: "Invited speaker for spark talk via Zoom",
    category: "talk",
    title: "Beyond the Algorithm: Building Trustworthy, Fair, and Useful AI in Health and Higher Education",
    venue: "Office of Artificial Intelligence Strategies, Innovation, and Success (OAISIS), Eastern Kentucky University, Richmond, KY, USA",
    authors: "Kakraba, S.",
    links: [{ label: "Watch the talk", href: "https://www.youtube.com/watch?v=eFluuNnTpdI&list=PL87KFqYs1CMITtqlPdVDdbjx-uA3sXRgr" }],
    mentorRole: "Senior mentor; supervised project design, modeling strategy, and abstract preparation",
  },
  {
    year: 2026,
    date: "September 11, 2026",
    role: "Invited speaker",
    category: "talk",
    title: "Scalable Multi-Target AI/ML Systems for Public Health Surveillance, Precision Prediction, and Drug Discovery",
    venue: "Biostatistics and Data Science Seminar Series, Department of Biostatistics and Data Science, Celia Scott Weatherhead School of Public Health and Tropical Medicine at Tulane University, New Orleans, LA, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2026,
    date: "August 13, 2026",
    role: "Invited speaker",
    category: "talk",
    title: "Practical AI Applications Use in Disease Surveillance/Epidemiology & Immunization",
    venue: "Louisiana Department of Health Artificial Intelligence Symposium, E. J. Ourso College of Business Executive Education, Louisiana State University, Baton Rouge, LA, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2026,
    date: "August 13, 2026",
    role: "Invited panelist",
    category: "panel",
    title: "Practical AI Tools for Louisiana Department of Health Workers: Ethical Implementation, Community Trust, and Workforce Efficiency",
    venue: "Louisiana Department of Health Artificial Intelligence Symposium, E. J. Ourso College of Business Executive Education, Louisiana State University, Baton Rouge, LA, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2026,
    date: "Spring 2026",
    role: "Invited poster",
    category: "poster",
    title: "Multiscale Predictive Modeling of SARS-CoV-2 Spike RBD Mutations: Structural and Functional Insights",
    venue: "Tulane Research, Innovation, & Creativity Summit (TRICS) 2026, Tulane University, New Orleans, LA, USA",
    authors: "Emma Darr, Edem K. Netsey, Samuel M. Naandam, Joseph Asante, Kuukua E. Abraham, Aayire C. Yadem, Gabriel Owusu, Jeffrey G. Shaffer, Sudesh K. Srivastav, Seydou Doumbia, Ellis Owusu-Dabo, Chris E. Morkle, Desmond Yemeh, Stephen Manortey, Ernest Yankson, Mamadou Sangare, Samuel Kakraba",
  },
  {
    year: 2026,
    date: "Spring 2026",
    role: "Invited poster",
    category: "poster",
    title: "Machine Learning–Driven Survival Prediction and Risk Stratification in Heart Failure",
    venue: "Tulane Research, Innovation, & Creativity Summit (TRICS) 2026, Tulane University, New Orleans, LA, USA",
    authors: "Samuel D. Assefa, Farhana Chaudhry, Edmund Agyemang, Daniela Candanedo, Bailey Taylor, Kevin Siliezar, Desmond Yemeh, Samuel Kakraba",
    mentorRole: "Senior mentor; guided ML pipeline development, feature engineering, and interpretation",
  },
  {
    year: 2026,
    date: "Spring 2026",
    role: "Invited poster",
    category: "poster",
    title: "Explainable Machine Learning for Predicting Workplace Mental Health Treatment-Seeking",
    venue: "Tulane Research, Innovation, & Creativity Summit (TRICS) 2026, Tulane University, New Orleans, LA, USA",
    authors: "Daniela Candanedo, Edmund Agyemang, Farhana Chaudhry, Taylor Franks, Bailey Taylor, Kevin Siliezar, Samuel Kakraba",
    mentorRole: "Senior mentor; guided ML pipeline development, feature engineering, and interpretation",
  },
  {
    year: 2026,
    date: "Spring 2026",
    role: "Invited poster",
    category: "poster",
    title: "Explainable Machine Learning for Improved Thyroid Cancer Recurrence Risk Stratification",
    venue: "Tulane Research, Innovation, & Creativity Summit (TRICS) 2026, Tulane University, New Orleans, LA, USA",
    authors: "Adeshola Lawal, Bailey Taylor, Samuel Kakraba",
    mentorRole: "Senior mentor; guided ML pipeline development, feature engineering, and interpretation",
  },
  {
    year: 2026,
    date: "Spring 2026",
    role: "Invited poster",
    category: "poster",
    title: "Machine Learning-Enhanced Quantitative Structure-Activity Relationship Modeling for DNA Polymerase Inhibitor Discovery: Algorithm Development and Validation",
    venue: "Tulane Research, Innovation, & Creativity Summit (TRICS) 2026, Tulane University, New Orleans, LA, USA",
    authors: "Desmond Yemeh, Samuel Kakraba, Srinivas Ayyadevara, Aayire Yadem Clement, Kuukua E. Abraham, Cesar M. Compadre, Robert J. Shmookler Reis",
    mentorRole: "Senior mentor; oversaw study design, data analysis, and clinical interpretation",
  },
  {
    year: 2026,
    date: "Spring 2026",
    role: "Invited poster",
    category: "poster",
    title: "Design and Evaluation of an AI-Enhanced Multi-Model R Shiny Application for Predictive Analytics in Alzheimer’s Disease",
    venue: "Tulane Research, Innovation, & Creativity Summit (TRICS) 2026, Tulane University, New Orleans, LA, USA",
    authors: "Edmund Fosu Agyemang, Han Wenzheng, Sudesh Srivastav, Jeffrey Shaffer, Samuel Kakraba",
    mentorRole: "Senior mentor; oversaw study design, data analysis, and clinical interpretation",
  },
  {
    year: 2026,
    date: "Spring 2026",
    role: "Invited poster",
    category: "poster",
    title: "Leveraging Machine Learning Algorithms and Explainable AI for Predicting Mental Health Disorder Treatment at the Workplace",
    venue: "Tulane Research, Innovation, & Creativity Summit (TRICS) 2026, Tulane University, New Orleans, LA, USA",
    authors: "Daniela Candanedo, Edmund Agyemang, Farhana Chaudhry, Taylor Franks, Bailey Taylor, Kevin Siliezar, Samuel Kakraba",
    mentorRole: "Senior mentor; supervised model selection, XAI methods, and narrative framing",
  },
  {
    year: 2026,
    date: "Spring 2026",
    role: "Invited poster",
    category: "poster",
    title: "Near-Perfect Survival Prediction in Pancreatic Cancer with Ensemble Machine Learning: Evidence from a SEER-Based African American Cohort",
    venue: "Tulane Research, Innovation, & Creativity Summit (TRICS) 2026, Tulane University, New Orleans, LA, USA",
    authors: "Subashini Muthaiah, Edmund F. Agyemang, Samuel Kakraba",
    mentorRole: "Senior mentor; oversaw ensemble modeling framework and equity-focused interpretation",
  },
  {
    year: 2026,
    date: "Spring 2026",
    role: "Invited poster",
    category: "poster",
    title: "A Comparative Analysis of Data Aggregation Approaches for Parkinson’s Disease Prediction Using Multi-Recording Voice Data and an Automated Artificial Intelligence Pipeline",
    venue: "Tulane Research, Innovation, & Creativity Summit (TRICS) 2026, Tulane University, New Orleans, LA, USA",
    authors: "Ema Akter, Zhengxiao Yang, Hao Zhou, Sudesh Srivastav, Jeffrey G. Shaffer, Kuukua E. Abraham, Samuel M. Naandam, and Samuel Kakraba",
    mentorRole: "Senior mentor; supervised comparative study design and pipeline implementation",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Keynote speaker",
    category: "talk",
    title: "Harnessing Artificial Intelligence for Faster Drug Discovery",
    venue: "11th Biennial Scientific Conference, KNUST, Kumasi, Ghana",
    authors: "Kakraba, S.",
    mentorRole: "Senior mentor; led concept, methods, and poster development",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited speaker",
    category: "talk",
    title: "Design and Implementation of Scalable and Equitable AI/ML Workflows for Population-Health Measurement and Disease Diagnostics to Improve Public Health Outcomes in Low-Resource Settings",
    venue: "AI Research Symposium: Demystifying AI in Public Health, Tulane University, New Orleans, LA, USA",
    authors: "Kakraba, S.",
    links: [{ label: "Symposium coverage", href: "https://sph.tulane.edu/demystifying-ai-public-health" }],
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited speaker",
    category: "talk",
    title: "Opportunities with AI/ML in Public Health",
    venue: "AI Research Symposium: Demystifying AI in Public Health, Tulane University, New Orleans, LA, USA",
    authors: "Kakraba, S.",
    links: [{ label: "Symposium coverage", href: "https://sph.tulane.edu/demystifying-ai-public-health" }],
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited poster",
    category: "poster",
    title: "AI-Enhanced Multi-Algorithm R Shiny App for Predictive Modeling and Analytics",
    venue: "AI Research Symposium, Tulane University, New Orleans, LA, USA",
    authors: "Agyemang, E., Wenzheng, H., Srivastav, S., Shaffer, J., Kakraba, S.",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited poster",
    category: "poster",
    title: "Optimizing Parkinson’s Disease Prediction",
    venue: "AI Research Symposium, Tulane University, New Orleans, LA, USA",
    authors: "Akter, E., Yang, Z., Zhou, H., Srivastav, S., Shaffer, J.G., Abraham, K.E., Naandam, S.M., Kakraba, S.",
    mentorRole: "Senior mentor; supervised modeling approach and results communication",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Poster",
    category: "poster",
    title: "Discovery of DNA Polymerase Inhibitors: ML-Enhanced QSAR Modeling Approach",
    venue: "AI Research Symposium, Tulane University, New Orleans, LA, USA",
    authors: "Yemeh, D., Kakraba, S., et al.",
    mentorRole: "Senior mentor; guided QSAR design and interpretation",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited poster",
    category: "poster",
    title: "Accelerating Discovery of Leukemia Inhibitors with AI-Driven QSAR Modeling",
    venue: "AI Research Symposium, Tulane University, New Orleans, LA, USA",
    authors: "Sivebukola, I.O., Kakraba, S., Shmookler Reis, R.J.",
    mentorRole: "Senior mentor; supervised project scope and presentation",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited poster",
    category: "poster",
    title: "Enhancing Thyroid Cancer Recurrence Risk Stratification with Explainable Machine Learning",
    venue: "AI Research Symposium, Tulane University, New Orleans, LA, USA",
    authors: "Taylor, B., Kakraba, S.",
    mentorRole: "Senior mentor; guided XAI methods and clinical messaging",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited poster",
    category: "poster",
    title: "Structural and Functional Impacts of SARS-CoV-2 Spike Protein Mutations",
    venue: "AI Research Symposium, Tulane University, New Orleans, LA, USA",
    authors: "Owusu, G., Netsey, E.K., et al., Kakraba, S.",
    mentorRole: "Senior mentor; oversaw analytic design and visualization",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited poster",
    category: "poster",
    title: "Leveraging ML and Explainable AI for Predicting Mental Health Disorder Treatment at the Workplace",
    venue: "AI Research Symposium, Tulane University, New Orleans, LA, USA",
    authors: "Candanedo, D., Agyemang, E., Chaudhry, F., Franks, T., Taylor, B., Siliezar, K., Kakraba, S.",
    mentorRole: "Senior mentor; supervised ML modeling and explainability framework",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited poster",
    category: "poster",
    title: "Enhancing Early Detection of Cervical Cancer: ML Prediction of Biopsy Outcomes",
    venue: "AI Research Symposium, Tulane University, New Orleans, LA, USA",
    authors: "Taylor, F., Kakraba, S.",
    mentorRole: "Senior mentor; guided model development and evaluation",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited poster",
    category: "poster",
    title: "Harnessing ML and Model Interpretability for Survival Prediction in Heart Failure Patients",
    venue: "AI Research Symposium, Tulane University, New Orleans, LA, USA",
    authors: "Chaudhry, F.S., Kakraba, S.",
    mentorRole: "Senior mentor; supervised survival modeling and XAI analyses",
  },
  {
    year: 2025,
    date: "Fall 2025",
    role: "Invited speaker",
    category: "talk",
    title: "Improving Student Visa Outcomes Before and After 214(b) Denials",
    venue: "Graduate Admissions, Celia Scott Weatherhead School of Public Health and Tropical Medicine, Tulane University, New Orleans, LA, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2025,
    date: "July 15, 2025",
    role: "Invited panelist",
    category: "panel",
    title: "Global Health Initiatives: University of Ghana Meets Tulane University",
    venue: "University of Ghana, Accra, Ghana",
    authors: "Kakraba, S.",
    links: [{ label: "University of Ghana coverage", href: "https://publichealth.ug.edu.gh/events/university-ghana-meets-tulane-university" }],
  },
  {
    year: 2025,
    date: "July 14, 2025",
    role: "Invited panelist",
    category: "panel",
    title: "Shaping the Future of Global Health: University of Cape Coast Meets Tulane University",
    venue: "University of Cape Coast, Cape Coast, Ghana",
    authors: "Kakraba, S.",
    links: [{ label: "UCC News coverage", href: "https://www.ucc.edu.gh/news/ucc-university-cincinnati-and-tulane-university-meet-deepen-academic-and-research-partnerships" }],
  },
  {
    year: 2025,
    date: "July 11, 2025",
    role: "Invited speaker",
    category: "talk",
    title: "Data Science as Powerful Transformational Tool for Enhanced Health Outcomes",
    venue: "School of Physical Sciences, University of Cape Coast, Cape Coast, Ghana",
    authors: "Kakraba, S.",
  },
  {
    year: 2025,
    date: "July 10, 2025",
    role: "Invited panelist",
    category: "panel",
    title: "Global Health Initiatives: Kwame Nkrumah University of Science and Technology Meets Tulane University",
    venue: "Kwame Nkrumah University of Science and Technology, Kumasi, Ghana",
    authors: "Kakraba, S.",
    links: [{ label: "KNUST News coverage", href: "https://www.knust.edu.gh/news/news-items/knust-tulane-university-sign-mou-deepen-academic-collaboration" }],
  },
  {
    year: 2025,
    date: "July 8, 2025",
    role: "Invited panelist",
    category: "panel",
    title: "Future of Global Public Health Research and Practice",
    venue: "Ensign Global University, Kpong, Ghana",
    authors: "Kakraba, S.",
    links: [{ label: "Tulane SPH coverage", href: "https://sph.tulane.edu/celia-scott-weatherhead-school-develops-academic-relationships-schools-ghana" }],
  },
  {
    year: 2025,
    date: "April 10, 2025",
    role: "Invited lightning talk",
    category: "talk",
    title: "Harnessing AI to Revolutionize Diagnostics and Drug Discovery for Neurodegenerative and Other Diseases",
    venue: "3rd Annual TRICS, Tulane University, New Orleans, LA, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2025,
    date: "April 9, 2025",
    role: "Invited poster",
    category: "poster",
    title: "Harnessing AI to Revolutionize Diagnostics and Drug Discovery",
    venue: "3rd Annual TRICS, Tulane University, New Orleans, LA, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2025,
    date: "April 4, 2025",
    role: "Invited webinar",
    category: "talk",
    title: "Revolutionizing Public Health: Predictive AI-Enhanced Workflows",
    venue: "Ensign Global University, Kpong, Ghana",
    authors: "Kakraba, S.",
  },
  {
    year: 2024,
    date: "December 2, 2024",
    role: "Invited speaker",
    category: "talk",
    title: "Harnessing AI for Enhanced Health Outcomes",
    venue: "Medical Grand Rounds, Tulane School of Medicine, New Orleans, LA, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2024,
    date: "November 13, 2024",
    role: "Invited speaker",
    category: "talk",
    title: "Design and Implementation of AI-Powered Pipelines for Predictive Modeling",
    venue: "Public Health Discovery Seminar Series, Tulane University, New Orleans, LA, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2024,
    date: "June 2024",
    role: "Invited poster",
    category: "poster",
    title: "Identifying and Designing Better DNA Polymerase Inhibitors Using ML-Oriented QSAR",
    venue: "10th Drug Discovery Colloquium (DDC)/MALTO, University of Arkansas for Medical Sciences, Little Rock, AR, USA",
    authors: "Abraham, E.K., Kakraba, S., et al.",
  },
  {
    year: 2024,
    date: "June 2024",
    role: "Invited poster",
    category: "poster",
    title: "Modeling Anti-Aggregative Activity of Quinoline Analogs",
    venue: "10th DDC/MALTO, University of Arkansas for Medical Sciences, Little Rock, AR, USA",
    authors: "Zhou, H., Kakraba, S., et al.",
  },
  {
    year: 2024,
    date: "June 2024",
    role: "Invited poster",
    category: "poster",
    title: "ML-Driven QSAR to Model Anti-Leukemic Activity of TDZD Family",
    venue: "10th DDC/MALTO, University of Arkansas for Medical Sciences, Little Rock, AR, USA",
    authors: "Yang, Z., Kakraba, S., et al.",
  },
  {
    year: 2024,
    date: "June 2024",
    role: "Invited workshop",
    category: "workshop",
    title: "Building Machine Learning Pipelines for Predictive Modeling and Analytics",
    venue: "DDC/MALTO, University of Arkansas for Medical Sciences, Little Rock, AR, USA",
    authors: "Kakraba, S., Yang, Z., Zhou, H.",
    links: [{ label: "UAMS News coverage", href: "https://news.uams.edu/2024/07/09/two-research-conferences-converge-at-uams-for-young-scientists" }],
  },
  {
    year: 2023,
    date: "2023",
    role: "Invited poster",
    category: "poster",
    title: "Computer-Aided Drug Discovery to Modeling the Inhibition of Protein Aggregation",
    venue: "19th Annual MCBIOS Conference, USA",
    authors: "Kakraba, S., et al.",
  },
  {
    year: 2022,
    date: "Fall 2022",
    role: "Guest speaker",
    category: "talk",
    title: "Application of Machine Learning to Drug Discovery and Design",
    venue: "Eastern Kentucky University, Richmond, KY, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2022,
    date: "July 2022",
    role: "Oral presentation",
    category: "talk",
    title: "Temperature Effect on the Structural Dynamics of SARS-CoV-2 Nucleocapsid Domain",
    venue: "23rd Intl BIOCOMP’22, USA",
    authors: "Naandam, S.M., Gogovi, G.K., Kakraba, S.",
  },
  {
    year: 2022,
    date: "2022",
    role: "Invited speaker",
    category: "talk",
    title: "Application of ML to Modeling of the Inhibition of Protein Aggregation",
    venue: "18th Annual MCBIOS, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2022,
    date: "February 2022",
    role: "Invited colloquium speaker",
    category: "talk",
    title: "A Mathematical Graph-Theoretic Model of Single Point Mutations Associated with Sickle Cell Anemia Disease",
    venue: "Eastern Kentucky University, Richmond, KY, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2021,
    date: "September 2021",
    role: "Colloquium talk",
    category: "talk",
    title: "Application of Machine Learning in Drug Design and Discovery",
    venue: "Eastern Kentucky University, Richmond, KY, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2019,
    date: "November 2019",
    role: "Oral presentation",
    category: "talk",
    title: "Using QSAR Approach for Identifying Novel Drugs for Treatment of Neurodegenerative Diseases",
    venue: "Southeast Regional IDeA Conference, Louisville, KY, USA",
    authors: "Kakraba, S., et al.",
  },
  {
    year: 2019,
    date: "November 2019",
    role: "Oral presentation",
    category: "talk",
    title: "Identification of Novel Drugs for Treatment of Neurodegenerative Diseases by QSAR Approach",
    venue: "DDC/MALTO, UALR, Little Rock, AR, USA",
    authors: "Kakraba, S., et al.",
  },
  {
    year: 2019,
    date: "June 2019",
    role: "Poster",
    category: "poster",
    title: "A Novel Microtubule-Binding Drug Attenuates and Reverses Protein Aggregation",
    venue: "22nd Intl C. elegans Conference, Los Angeles, CA, USA",
    authors: "Ayyadevara, S., Kakraba, S., et al.",
  },
  {
    year: 2019,
    date: "2019",
    role: "Poster",
    category: "poster",
    title: "Aggregate Interactome Based on Protein-Crosslinking Interfaces",
    venue: "NSF meeting, Chicago, IL, USA",
    authors: "Balasubramaniam, M., Kakraba, S., et al.",
  },
  {
    year: 2018,
    date: "June 2018",
    role: "Invited poster",
    category: "poster",
    title: "Identifying Novel Drugs for Treatment of Neurodegenerative Diseases by QSAR Approach",
    venue: "NISBRE, Washington, DC, USA",
    authors: "Kakraba, S., et al.",
  },
  {
    year: 2018,
    date: "March 2018",
    role: "Invited poster",
    category: "poster",
    title: "Using QSAR in Drug Discovery",
    venue: "14th Annual MCBIOS, Starkville, MS, USA",
    authors: "Kakraba, S., et al.",
  },
  {
    year: 2017,
    date: "June 2017",
    role: "Invited poster",
    category: "poster",
    title: "Screening and Characterization of Drugs to Block Protein Aggregation",
    venue: "Southeast Regional IDeA Conference, WVU, Morgantown, WV, USA",
    authors: "Kakraba, S., et al.",
  },
  {
    year: 2017,
    date: "June 2017",
    role: "Invited poster",
    category: "poster",
    title: "Drugs to Block Protein Aggregation in Neurodegenerative Diseases",
    venue: "DDC, UAMS, Little Rock, AR, USA",
    authors: "Kakraba, S., et al.",
  },
  {
    year: 2017,
    date: "June 2017",
    role: "Invited poster",
    category: "poster",
    title: "Design and Synthesis of Cyanoresveratrol Analogs",
    venue: "DDC/MALTO, UAMS, Little Rock, AR, USA",
    authors: "Bowroju, K.S., Kakraba, S., et al.",
  },
  {
    year: 2017,
    date: "May 2017",
    role: "Invited poster",
    category: "poster",
    title: "P16-Synthesis and Evaluation of Novel Drug Molecules",
    venue: "MALTO, University of Louisiana Monroe, Monroe, LA, USA",
    authors: "Bowroju, K.S., Kakraba, S., et al.",
  },
  {
    year: 2017,
    date: "March 2017",
    role: "Invited poster",
    category: "poster",
    title: "Screening and Characterization of Small Molecules that Reduce Amyloid Aggregation",
    venue: "14th Annual MCBIOS, Little Rock, AR, USA",
    authors: "Kakraba, S., et al.",
  },
  {
    year: 2016,
    date: "June 2016",
    role: "Invited guest speaker",
    category: "talk",
    title: "Drug Design and Discovery",
    venue: "MAA SUMMA Program, ETSU, Johnson City, TN, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2016,
    date: "June 2016",
    role: "Invited speaker",
    category: "talk",
    title: "Effects of Small Molecules on Protein Aggregation and Paralysis in C. elegans",
    venue: "NISBRE, Washington, DC, USA",
    authors: "Kakraba, S.",
  },
  {
    year: 2016,
    date: "April 2016",
    role: "Invited poster",
    category: "poster",
    title: "Effects of Small Molecules on Protein Aggregation",
    venue: "AR-BIC Second Annual Conference, Little Rock, AR, USA",
    authors: "Kakraba, S., et al.",
  },
  {
    year: 2015,
    date: "November 2015",
    role: "Invited speaker",
    category: "talk",
    title: "Association of Alcohol Consumption and Skin Allergy with Non-Melanoma Skin Cancer",
    venue: "2015 Southeast Regional IDeA Meeting, Biloxi, MS, USA",
    authors: "Kakraba, S., Ke-Sheng Wang",
  },
  {
    year: 2015,
    date: "March 2015",
    role: "Invited speaker",
    category: "talk",
    title: "A Graph-Theoretic Model of Nucleotide-Binding Domain 2 of the CFTR",
    venue: "13th Annual MCBIOS Conference, Memphis, TN, USA",
    authors: "Kakraba, S., Knisley, J.D.",
  },
];
